POST http://localhost:3005/api/blogs
content-type: application/json

{
    "title" :"Hello tryout",
    "author" : "imri",
    "url" : "123",
    "likes" : 10,
    "userId": "6076a4a2efa2b31ca075b2ee"
}
####
PUT http://localhost:3005/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
"_id": "5a422a851b54a676234d17f7",
"title": "React patterns",
"author": "Michael Chan",
"url": "https://reactpatterns.com/",
"likes": 10,
"__v": 0
}

####
POST http://localhost:3005/api/users
content-type: application/json

{
    "name": "imri",
    "username": "Loli Lolo",
    "password":"12323"
}
####
POST http://localhost:3005/api/login 
content-type: application/json

{
    "username":"hi",
    "password":"123123"
}
#####
POST http://localhost:3005/api/login 
content-type: application/json

{
    "username":"Loli Lolo",
    "password":"12323"
}
####
POST http://localhost:3005/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxvbGkgTG9sbyIsImlkIjoiNjA3YzI3YTVhNzEzM2U0Yjk4MDBiZjMyIiwiaWF0IjoxNjE4NzYzNTA5fQ.QJ7ewRll87bl3-M7cMhcJ_Yh7xkMBwuEBf3zmeF1RDM

{
    "title" :"DELETEME",
    "author" : "token",
    "url" : "123",
    "likes" : 10
}
####
DELETE http://localhost:3005/api/blogs/607b0001615a6a33b0524c2b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbmEiLCJpZCI6IjYwN2FkOWIyYmVkNTY5M2Y2Y2NlOWU3MSIsImlhdCI6MTYxODY2NTc3MH0.uT4jgsDou32DC7eoU57Mggf4XH0LEv31s6K3tpnQWWc


